---
language: python
services: docker

env:
  global:
    - ROLE_NAME: bootstrap
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME williampiv.$ROLE_NAME
  - cd williampiv.$ROLE_NAME


script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
