---
- name: Configure SELinux for Ansible on CentOS/RHEL/Fedora (Python 3)
  when: ansible_distribution_major_version == '8'
  yum:
    name: libselinux-python3
    state: present

- name: Configure SELinux for Ansible on CentOS/RHEL/Fedora (Python 2)
  when: ansible_distribution_major_version < '8'
  yum:
    name: libselinux-python
    state: present
